package steps;

import config.ApiConfig;
import context.ScenarioContext;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.closeTo;
import static org.hamcrest.Matchers.is;

public class SubscriptionsSteps {

    private final ScenarioContext ctx;

    public SubscriptionsSteps(ScenarioContext ctx) {
        this.ctx = ctx;
    }

    /** Creates an active WITHDRAWAL recurring rule carrying a merchant, so it can be
     *  detected as a rule-based subscription. RecurringSteps' body builder omits
     *  "merchant", so this class builds its own request. */
    @Given("an active recurring {string} rule with merchant {string} and amount {double} and frequency {string} exists for the account")
    public void anActiveRecurringRuleWithMerchantExistsForTheAccount(String type, String merchant, double amount, String frequency) {
        String startDate = Instant.now().plus(30, ChronoUnit.DAYS).truncatedTo(ChronoUnit.MILLIS).toString();
        Map<String, Object> body = new HashMap<>();
        body.put("accountId", ctx.getString("accountId"));
        body.put("name", merchant + " subscription");
        body.put("merchant", merchant);
        body.put("type", type);
        body.put("amount", amount);
        body.put("category", "Subscription");
        body.put("description", merchant + " generated by API tests");
        body.put("frequency", frequency);
        body.put("startDate", startDate);

        Response response = RestAssured
            .given(baseRequest())
                .body(body)
            .when()
                .post(ApiConfig.RECURRING_PATH)
            .then()
                .extract().response();
        assertThat(response.statusCode(), is(201));
    }

    @When("the subscriptions summary is fetched")
    public void theSubscriptionsSummaryIsFetched() {
        Response response = RestAssured
            .given(baseRequest())
            .when()
                .get(ApiConfig.SUBSCRIPTIONS_PATH)
            .then()
                .extract().response();
        ctx.setLastResponse(response);
    }

    @When("the subscriptions summary is fetched without authentication")
    public void theSubscriptionsSummaryIsFetchedWithoutAuthentication() {
        Response response = RestAssured
            .given()
                .baseUri(ApiConfig.BASE_URL)
                .contentType(ContentType.JSON)
                .header("X-Internal-Secret", ApiConfig.INTERNAL_SECRET)
            .when()
                .get(ApiConfig.SUBSCRIPTIONS_PATH)
            .then()
                .extract().response();
        ctx.setLastResponse(response);
    }

    @Then("the subscriptions monthly total is {double}")
    public void theSubscriptionsMonthlyTotalIs(double expected) {
        assertThat(ctx.getLastResponse().jsonPath().getDouble("monthlyTotal"), is(expected));
    }

    @Then("the subscriptions count is {int}")
    public void theSubscriptionsCountIs(int expected) {
        assertThat(ctx.getLastResponse().jsonPath().getInt("count"), is(expected));
    }

    @Then("the subscriptions list includes merchant {string} with source {string} and monthly cost {double}")
    public void theSubscriptionsListIncludesMerchantWithSourceAndMonthlyCost(String merchant, String source, double monthlyCost) {
        List<Map<String, Object>> subscriptions = ctx.getLastResponse().jsonPath().getList("subscriptions");
        boolean match = subscriptions.stream().anyMatch(sub ->
            merchant.equals(sub.get("merchant")) &&
            source.equals(sub.get("source")) &&
            closeTo(monthlyCost, 0.01).matches(((Number) sub.get("monthlyCost")).doubleValue())
        );
        assertThat("Expected subscription not found", match, is(true));
    }

    private RequestSpecification baseRequest() {
        return RestAssured
            .given()
                .baseUri(ApiConfig.BASE_URL)
                .contentType(ContentType.JSON)
                .header("X-User-Id", ctx.getUserId())
                .header("X-Internal-Secret", ApiConfig.INTERNAL_SECRET);
    }
}
